#############################################################################
# Makefile for building: G15Manager
# Generated by qmake (2.01a) (Qt 4.8.6) on: dt. de set. 2 16:27:21 2014
# Project:  G15Manager.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile G15Manager.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu /usr/lib/libg15daemon_client.so /usr/lib/libg15render.so -lQtDBus -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		appletsManager.cpp \
		applets/amarokapplet.cpp \
		applets/applet.cpp \
		applets/audaciousapplet.cpp \
		applets/clementineapplet.cpp \
		applets/exaileapplet.cpp \
		applets/gmailapplet.cpp \
		applets/hardwareapplet.cpp \
		applets/processesapplet.cpp \
		applets/rhythmboxapplet.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		appletsManager.o \
		amarokapplet.o \
		applet.o \
		audaciousapplet.o \
		clementineapplet.o \
		exaileapplet.o \
		gmailapplet.o \
		hardwareapplet.o \
		processesapplet.o \
		rhythmboxapplet.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		G15Manager.pro
QMAKE_TARGET  = G15Manager
DESTDIR       = 
TARGET        = G15Manager

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: G15Manager.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtDBus.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile G15Manager.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtDBus.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile G15Manager.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/G15Manager1.0.0 || $(MKDIR) .tmp/G15Manager1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/G15Manager1.0.0/ && $(COPY_FILE) --parents mainwindow.h appletsManager.h applets/amarokapplet.h applets/applet.h applets/audaciousapplet.h applets/clementineapplet.h applets/exaileapplet.h applets/gmailapplet.h applets/hardwareapplet.h applets/processesapplet.h applets/rhythmboxapplet.h .tmp/G15Manager1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp appletsManager.cpp applets/amarokapplet.cpp applets/applet.cpp applets/audaciousapplet.cpp applets/clementineapplet.cpp applets/exaileapplet.cpp applets/gmailapplet.cpp applets/hardwareapplet.cpp applets/processesapplet.cpp applets/rhythmboxapplet.cpp .tmp/G15Manager1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/G15Manager1.0.0/ && (cd `dirname .tmp/G15Manager1.0.0` && $(TAR) G15Manager1.0.0.tar G15Manager1.0.0 && $(COMPRESS) G15Manager1.0.0.tar) && $(MOVE) `dirname .tmp/G15Manager1.0.0`/G15Manager1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/G15Manager1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: appletsManager.h \
		applets/applet.h \
		mainwindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		appletsManager.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		appletsManager.h \
		applets/applet.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

appletsManager.o: appletsManager.cpp appletsManager.h \
		applets/applet.h \
		applets/amarokapplet.h \
		applets/audaciousapplet.h \
		applets/clementineapplet.h \
		applets/exaileapplet.h \
		applets/gmailapplet.h \
		applets/hardwareapplet.h \
		applets/processesapplet.h \
		applets/rhythmboxapplet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appletsManager.o appletsManager.cpp

amarokapplet.o: applets/amarokapplet.cpp applets/amarokapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o amarokapplet.o applets/amarokapplet.cpp

applet.o: applets/applet.cpp applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o applet.o applets/applet.cpp

audaciousapplet.o: applets/audaciousapplet.cpp applets/audaciousapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audaciousapplet.o applets/audaciousapplet.cpp

clementineapplet.o: applets/clementineapplet.cpp applets/clementineapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clementineapplet.o applets/clementineapplet.cpp

exaileapplet.o: applets/exaileapplet.cpp applets/exaileapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exaileapplet.o applets/exaileapplet.cpp

gmailapplet.o: applets/gmailapplet.cpp applets/gmailapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gmailapplet.o applets/gmailapplet.cpp

hardwareapplet.o: applets/hardwareapplet.cpp applets/hardwareapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hardwareapplet.o applets/hardwareapplet.cpp

processesapplet.o: applets/processesapplet.cpp applets/processesapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processesapplet.o applets/processesapplet.cpp

rhythmboxapplet.o: applets/rhythmboxapplet.cpp applets/rhythmboxapplet.h \
		applets/applet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rhythmboxapplet.o applets/rhythmboxapplet.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

